### ISSUE TITLE
RuleError should have "detail/message" field

### ISSUE THREAD

**Issue by MeirionHughes** [MeirionHughes/template-lint#13]
Would be nice to be able to return detail/messages for errors; for example the the obsolete tag could return a message about what the tag was replaced with.

**Comment by atsu85** [comment]
Yesterday I was also thinking about adding Rule subclass name to the `RuleError` class in case of failure, so that it could be used as a link to specific rule violation explained in detail on the website and potentially also in "integration" tests, that may want to create linter with more than one rule.

**Comment by MeirionHughes** [comment]
yeah that might be useful
